CCI-MIT/XCoLab

portlets/proposals-portlet/pom.xml
Version 3.2.1 has a CVSS 10.0 vulnerability. That is the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8103
https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/
=> Upgrade Apache Commons Collections to v3.2.2

view/src/main/webapp/WEB-INF/jsp/proposals/contestProposals.jspx
Creating a proposal was already possible as an admin. I just had to activate the button.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/16)
=> [COLAB-2109] Allow admins to create propsoals in closed phases

view/src/main/webapp/WEB-INF/jsp/profile/editUserProfile.jspx
Fixed the issue by turned off HTML escpaing in the error message form.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/17)
=> [COLAB-2177] Error message includes HTML code

view/src/main/resources/static/sass/partials/base/_layout.scss, view/src/main/resources/static/sass/partials/pages/_userprofile.scss
This PR fixes the bug that images can be bigger than the content box.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/20)
=> [COLAB-2195] fixed bio images max-width

microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/pojo/Contest.java, sql/deployments/deployment-2017-08-31__ClimateCoaLab.sql, sql/starter/xcolab-schema.sql, view/src/main/java/org/xcolab/view/pages/contestmanagement/beans/ContestBatchBean.java, view/src/main/java/org/xcolab/view/pages/contestmanagement/beans/ContestDescriptionBean.java, view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/BatchCreationController.java, view/src/main/webapp/WEB-INF/jsp/contestmanagement/batch/uploadContestCSV.jspx, view/src/main/webapp/WEB-INF/jsp/contestmanagement/details/descriptionTab.jspx, view/src/main/webapp/WEB-INF/jsp/proposals/contestProposals/header_contest_details.jspx
This PR implements linkable sponsor logos. On contest creation/edit, a sponsor link can be set. If a sponsor link is set, clicking on the sponsor logo of a contest will open the sponsor link URL in a new tab/window.
The sponsorLink field was already present in the database schema. I've adapted the VARCHAR length from 75 to 2000 to allow for longer URLs.
For the sake of consistency, I've renamed the "Organization/company logo" property field in the edit contest view to "Sponsor Logo".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/21)
=> [COLAB-1245] Add links to sponsor logos

microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/ContestTeamMemberClient.java, microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/ContestTeamMemberClientUtil.java, microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/pojo/Contest.java, microservices/services/contest-service/src/main/java/org/xcolab/service/contest/domain/contestteammember/ContestTeamMemberDao.java, microservices/services/contest-service/src/main/java/org/xcolab/service/contest/domain/contestteammember/ContestTeamMemberDaoImpl.java, microservices/services/contest-service/src/main/java/org/xcolab/service/contest/web/ContestTeamMembersController.java, view/src/main/java/org/xcolab/view/pages/contestmanagement/wrappers/ContestTeamWrapper.java
This PR implements automatic platform-wide role deletion. If a user is removed from a contest's team members and does not have that specific role in any other contest, this role is removed for the user on the whole platform.
To allow to perform this check, the `findByGiven` method in the `ContestTeamMemberDao` now has three parameters instead of one: `Long userId, Long contestId, Long roleId`. If any of them is null, it is not included in the query. On the client side, the same now applies to `getTeamMembers`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/25)
=> [COLAB-1176] Automatic Platform-wide Role Deletion

view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/SchedulesTabController.java, view/src/main/java/org/xcolab/view/pages/contestmanagement/wrappers/ContestScheduleBean.java, view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/schedulesTab.jspx
This PR implements a contest schedule validity check when an admin user tries to change a schedule. If the start date of a contest phase is not equal to the end date of the previous contest phase, the changed schedule is not saved an a warning is displayed.
Additionally, the client side is modified to complement those changes. When a contest start date is changed, the previous contest end date is automatically set to that same date. The end date input field is now disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/24)
=> [COLAB-2107] Check Contest Schedule Validity

microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/pojo/phases/AbstractContestPhaseType.java, microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/pojo/phases/ContestPhase.java, microservices/services/contest-service/src/main/java/org/xcolab/service/contest/domain/contestphasetype/ContestPhaseTypeDaoImpl.java, sql/deployments/deployment-2017-09-07__ClimateCoLab.sql, sql/starter/xcolab-schema.sql, view/src/main/webapp/WEB-INF/tags/proposalsPortlet/contestGridElement.tagx
This PR adds the `defaultFlagText` field to the ContestPhaseType. Now, when a Contest does not have a `flagText` set, the `defaultFlagText` of its contest phase's type is displayed instead of the `name`.  If the contest phase's type has no `defaultFlagText` set, the flag text falls back to the `name`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/26)
=> [COLAB-962] Add defaultFlagText to ContestPhaseType

view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/OverviewTabController.java, view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/overviewTab.jspx
This PR implements an automatic asynchronous contest order update on contest order change over AJAX. A new void-returning controller method is added at the route `"manager/updateOrder"` for performance reasons, since the returned data of `"manager/update"` is not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/27)
=> [COLAB-959] Autosave Contest Order Change

view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/schedulesTab.jspx
This PR reverts the frontend changes of [COLAB-2107]. The end date of the previous contest phase is now not set automatically anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/28)
=> [COLAB-2107] Revert contest phase overlap frontend changes

view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/ConfirmMassActionController.java, view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/OverviewTabController.java, view/src/main/java/org/xcolab/view/pages/contestmanagement/wrappers/ContestOverviewWrapper.java, view/src/main/java/org/xcolab/view/pages/contestmanagement/wrappers/MassActionConfirmationWrapper.java, view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/massActionConfirmation/confirmMassAction.jspx, view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/overviewTab.jspx
This PR changes a mapping of the mass action select dropdown to the selected mass action class from the mass action index to the mass action name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/34)
=> [COLAB-2238] Use Name to Map to Mass Action

microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/pojo/Contest.java, view/src/main/webapp/WEB-INF/jsp/widgets/contests/showContests.jspx
This pull requests fixes a display issue when a contest shown in the contest widget has no image set. Previously, it would show a broken placeholder image; now it shows the default contest image (as it would in other places on the site).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/36)
=> COLAB-2255 Contest widget default image

microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/pojo/Contest.java, microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/pojo/templates/AbstractPlanSectionDefinition.java, microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/Proposal.java, microservices/services/contest-service/src/main/java/org/xcolab/service/contest/domain/plansectiondefinition/PlanSectionDefinitionDaoImpl.java, sql/deployments/deployment-2017-10-02.sql, sql/starter/xcolab-schema.sql, view/src/main/java/org/xcolab/view/pages/contestmanagement/wrappers/SectionDefinitionWrapper.java, view/src/main/java/org/xcolab/view/pages/proposals/judging/ProposalReviewCsvExporter.java, view/src/main/java/org/xcolab/view/pages/proposals/view/action/JudgingCsvController.java, view/src/main/java/org/xcolab/view/util/entity/EntityIdListUtil.java, view/src/main/resources/static/sass/partials/bootstrap/_form.scss, view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/proposalTemplateTab.jspx
This pull requests adds the content of the pitch field (present in all proposals) to the judging CSV and adds the possibility to indicate that a template section should also be included in the report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/38)
=> COLAB-2253 Add fields to judging CSV

view/src/main/java/org/xcolab/view/pages/proposals/view/action/SupportProposalActionController.java
This PR fixes the issue that the supporter count would sometimes not update after clicking the (retract) support button on a proposal's details page by clearing the `MISC_REQUEST` cache when the support button is clicked..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/40)
=> [COLAB-2249] Fix Supporter Count Refresh

view/src/main/resources/static/sass/partials/base/_b-typography.scss, view/src/main/resources/static/sass/partials/components/_c-Badge.scss, view/src/main/resources/static/sass/partials/pages/_contests.scss, view/src/main/resources/static/sass/partials/themes/_t-climateRisksColab.scss, view/src/main/resources/static/sass/partials/themes/_t-crowdsensor.scss, view/src/main/resources/static/sass/partials/themes/_t-solveColab.scss, view/src/main/webapp/WEB-INF/jsp/proposals/contestsIndex/header-cards.jspx, view/src/main/webapp/WEB-INF/tags/layout.tagx
This pull request removes the Bree (Serif) fonts from the Climate CoLab. All references to these fonts are removed and will inherit the global default font.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/41)
=> [COLAB-2248] Remove Bree Serif font

microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/ProposalClient.java, microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/ProposalClientUtil.java, view/src/main/java/org/xcolab/view/pages/proposals/utils/picker/ProposalPickerFilterUtil.java
This pull request filters proposal from private contests when requesting proposals for the proposal picker. The microservice already supported the attribute, so I just added it to the client method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/43)
=> [COLAB-2266] Filter proposals from private contests in proposal picker

microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/domain/proposal/ProposalDao.java, microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/domain/proposal/ProposalDaoImpl.java, microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/service/proposal/ProposalService.java
This PR adds visibility conditions to the query that populates the proposal list in the user profile view:
1. Proposal visibility (in any phase)
2. Contest visibility (set via `contestPrivate` field)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/48)
=> [COLAB-2324] Hide proposals from private contests in profile

view/src/main/java/org/xcolab/view/auth/AuthenticationService.java, view/src/main/java/org/xcolab/view/auth/handlers/AuthenticationSuccessHandler.java, view/src/main/java/org/xcolab/view/config/spring/beans/WebSecurityBeansConfig.java, view/src/main/java/org/xcolab/view/pages/loginregister/LoginRegisterService.java, view/src/main/java/org/xcolab/view/pages/profile/view/UserProfileController.java, view/src/main/java/org/xcolab/view/pages/redballon/utils/BalloonService.java, view/src/main/java/org/xcolab/view/pages/redballoon/utils/BalloonCookie.java, view/src/main/java/org/xcolab/view/pages/redballoon/utils/BalloonService.java, view/src/main/java/org/xcolab/view/pages/redballoon/web/BalloonController.java, view/src/main/java/org/xcolab/view/pages/redballoon/web/beans/UserEmailBean.java, view/src/test/java/org/xcolab/view/pages/loginregister/ForgotPasswordControllerTest.java, view/src/test/java/org/xcolab/view/pages/loginregister/LoginRegisterControllerTest.java
This PR adds a call to the AuthenticationSuccessHandler when authenticating programmatically via the AuthenticationService. It includes some small refactoring to allow for the success handler not to redirect and to allow for the circular dependency between the success handler and service (there's a separate task to rethink this structure).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/51)
=> [COLAB-2359] login link logins not recorded

view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails/proposalSummary.jspx
This PR adds links to the share message for proposals.
Additional changes:
* Fix display of contest name (use short name instead of contest question)
* Change mentions of "proposal" and "contest" to lower in line with our capitalization guidelines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/55)
=> [COLAB-2375] share message link

view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java, view/src/main/java/org/xcolab/view/pages/members/users/MembersController.java, view/src/main/java/org/xcolab/view/util/CsvResponseWriter.java, view/src/main/java/org/xcolab/view/widgets/feeds/FeedsDumpGeneratingController.java
This PR ensures that all CsvWriters are being closed as otherwise they might not flush all content to the response before it is sent. Additionally, extracts a cleanRow method and applies it to the header row as well to make sure no illegal characters or unquoted strings are written.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/56)
=> [COLAB-2361] csvs cut off

view/src/main/java/org/xcolab/view/pages/proposals/utils/ProposalSortColumn.java, view/src/main/java/org/xcolab/view/pages/proposals/view/contest/ContestProposalsController.java, view/src/main/java/org/xcolab/view/pages/proposals/wrappers/ProposalsSortFilterBean.java, view/src/main/java/org/xcolab/view/pages/proposals/wrappers/SortedProposalList.java, view/src/main/webapp/WEB-INF/jsp/proposals/contestProposals.jspx
This PR simplifies the `ProposalsSortFilterBean` (now `SortedProposalList`) class, which did not need to be mutable and had some duplicate code (the comparator was initialized twice, overwriting the first initialization).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/57)
=> [COLAB-2379] Refactor proposal sorting

view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/overviewTab.jspx
This PR fixes the issue that the mass action edit form would not show up when the user selects a mass action that should trigger an edit form show.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/65)
=> [COLAB-2377] Bugfix: MassAction form not showing up

view/src/main/java/org/xcolab/view/pages/proposals/utils/context/ProposalContextHelper.java, view/src/main/java/org/xcolab/view/pages/proposals/utils/context/ProposalContextImpl.java, view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails.jspx
This PR fixes a permission problem when reopening a proposal in a new contest. The permissions class was using the ContestPhase from the source contest to evaluate permissions to create proposals in the new contest, which prevented reopening proposals from closed contests for non-admins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/69)
=> [COLAB-2420] Fix permissions for reopening proposals

microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/Proposal.java, view/src/main/java/org/xcolab/view/pages/proposals/utils/context/ProposalContextHelper.java, view/src/main/java/org/xcolab/view/pages/proposals/utils/context/ProposalContextImpl.java, view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/tabs/ProposalDescriptionTabController.java
This PR fixes the proposal-contest mapping when copying a proposal. The context proposal did not previously reference the context contest (i.e. the target contest), but did instead reference the source contest. This lead to a problem with checking if the sections changed.
~Depends on #69.~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/70)
=> [COLAB-2408] Fix section copying when moving proposals

sql/deployments/deployment-2017-11-15.sql, view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/SchedulesTabController.java, view/src/main/java/org/xcolab/view/pages/contestmanagement/wrappers/ContestScheduleBean.java, view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/schedulesTab.jspx
This PR removes the end date editing field from the Contest Management Tool Schedules Tab. End dates are now automatically set by the controller to the start date of the following phase.
The included SQL deployment script fixes wrong end dates by setting all end dates to the start dates of the following phase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/71)
=> [COLAB-2383] Remove end dates from schedules

microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/domain/proposalattribute/ProposalAttributeDaoImpl.java
This PR fixes the bug that old proposal attribute versions were not retrieved from the database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/72)
=> Bugfix: COLAB-2435 Proposal attributes of old versions not retrieved from database

view/src/main/java/org/xcolab/view/pages/contestmanagement/wrappers/PlatformTeamBean.java, view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/teamsTab.jspx
This PR limit team name length to 35 chars in the Contest Management Systems Teams Tab.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/75)
=> COLAB-2386: Limit team name length to 35 chars

microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/Proposal.java, view/src/main/java/org/xcolab/view/pages/proposals/utils/context/ProposalContextHelper.java
This PR fixes the bug that clicking the version picker has no effect. Now, clicking a version in the picker results in that proposal version being displayed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/80)
=> COLAB-2407: Fix proposal version picker

microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/ProposalAttributeClient.java, microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/ProposalAttributeClientUtil.java, microservices/util/entity-utils/src/main/java/org/xcolab/entity/utils/LinkUtils.java, view/src/main/java/org/xcolab/view/pages/loginregister/LoginRegisterController.java, view/src/main/java/org/xcolab/view/pages/loginregister/LoginRegisterService.java, view/src/main/java/org/xcolab/view/pages/loginregister/singlesignon/FacebookController.java, view/src/main/java/org/xcolab/view/pages/loginregister/singlesignon/GoogleController.java, view/src/test/java/org/xcolab/entity/utils/LinkUtilsTest.java
This PR fixes a redirect loop when google displays the account chooser (i.e. when you're signed into more than one Google account). This was caused by the AuthenticationSuccessHandler always redirecting to the referrer.
This PR also makes sure the redirect URL is always a relative url, as absolute urls don't make sense.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/79)
=> [COLAB-2436] Fix redirect loop in Google sign in

microservices/services/tracking-service/src/main/java/org/xcolab/service/tracking/domain/trackedvisitor2user/TrackedVisitor2UserDao.java, microservices/services/tracking-service/src/main/java/org/xcolab/service/tracking/domain/trackedvisitor2user/TrackedVisitor2UserDaoImpl.java, microservices/services/tracking-service/src/main/java/org/xcolab/service/tracking/service/TrackedVisitService.java, microservices/services/tracking-service/src/main/java/org/xcolab/service/tracking/service/TrackedVisitor2UserService.java, sql/deployments/deployment-2017-11-26.sql, sql/starter/xcolab-schema.sql
This PR restores and old feature that could link tracked visitors to accounts when they log in. There were two errors here:
1. New TrackedVisitors were not being created at all
2. Existing TrackedVisitors were never updated with a userId
~Depends on #76.~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/78)
=> [COLAB-2441] Fix association of tracked visitors with users

view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails_edit.jspx
This PR fixes the Discard button on the proposal edit view. Previously, this button would result in a reload of the edit view page. Now, the user is redirected to the proposal details view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/84)
=> [COLAB-2438] Discard Button closes Proposal Edit View

view/src/main/java/org/xcolab/view/pages/profile/view/UserProfileController.java
This PR changes the behavior of the save button in the edit profile view. If the edit was successful, the user is redirected to the profile view instead of the edit profile view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/82)
=> [COLAB-2393] Edit Profile Save Button Redirects to Profile View

microservices/clients/members-client/src/main/java/org/xcolab/client/members/MembersClient.java, microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/member/MemberDaoImpl.java
This PR fixes the member list name sort order. If the configuration attribute key `DISPLAY_FIRST_NAME_LAST_NAME` is set to `true`, the name-sorted member list is sorted by display name instead of `screenName`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/85)
=> [COLAB-2325] Fix member list name sort order

view/src/main/webapp/WEB-INF/jsp/members/usersIndex/header.jspx, view/src/main/webapp/WEB-INF/jsp/members/usersIndex/list.jspx
This PR fixes the issue that the member search only works on the first page and the search filter being removed on subsequent pages or sorting changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/86)
=> [COLAB-2311] Bugfix for member search

microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/phases/ProposalContestPhaseAttribute.java, view/src/main/java/org/xcolab/view/pages/profile/beans/BadgeBean.java
This PR fixes how the year of a ribbon is retrieved. This used to be based on the latest contest a proposal is in, which is a problem when the proposal has been moved out of the contest in which it received a ribbon.
The main difference is that instead of calling `ProposalClientUtil.getCurrentContestForProposal(long)`, we now get the phase from the `ProposalContestPhaseAttribute` and then call `phase.getContest()`. Since we need the attribute for that, this PR also extracts the attribute retrieval into a separate function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/95)
=> [COLAB-2519] Fix retrieval of ribbon year

view/src/main/resources/static/js/configureCkEditor.js
This PR fixes a bug where the char counter in the proposal editor is too high.
The reason for this bug is that CKEditor inserts zero width spaces (ZWS) (\u200b) into the text, which survive the jQuery.trim and therefore are being counted as well. With this PR, the ZWS are not being counted against the char limit anymore.
See [here](https://bugs.webkit.org/show_bug.cgi?id=15256) for more info about the ZWS insertion in CKEditor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/102)
=> [COLAB-2458] Bugfix: Wrong Proposal Editor Character Coung

view/src/main/resources/static/sass/partials/components/_c-ContestBox.scss, view/src/main/webapp/WEB-INF/jsp/widgets/contests/showContests.jspx
Fixed the issue in the contest widget. I did not find the same issue in other parts of the application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/99)
=> [COLAB-2268] Add default image size to Contest widget

view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/overviewTab.jspx
I imagine the css class was removed for some reason. I now find the correct input element by "type" and "name".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/100)
=> [COLAB-2498] Fix select all button in contest management overview

microservices/services/members-service/src/main/java/org/xcolab/service/members/domain/messaging/MessageDaoImpl.java
This PR fixes the message counting endpoint - it used to add a join to the recipients table even when not adding conditions on that table, which lead to an over count for messages with more than one recipient.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/109)
=> [COLAB-2557] Fix counting endpoint for messages

view/src/main/java/org/xcolab/view/pages/contestmanagement/utils/ProposalCsvWriter.java, view/src/main/java/org/xcolab/view/util/CsvResponseWriter.java
This PR adds a few extra fields to the proposal export. Most notably, it now also exports content. Since different contests have different sections, the amount of columns for the section data is flexible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/113)
=> [COLAB-2570] Improved proposal export

scripts/run/startServices.sh, scripts/run/stopServices.sh
Add quotation marks to shell commands to support file paths which contain spaces
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/150)
=> Fix start up warnings

view/src/main/java/org/xcolab/view/pages/proposals/utils/ContestsColumn.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/169)
=> [COLAB-2920]: reversed default sort order of contests by weight

view/src/main/webapp/WEB-INF/tags/layout/footer.tagx
I cannot test if this prevents the bug, but it's a further check to prevent any errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/180)
=> [COLAB-2952]: add null check for localStorage
