CCI-MIT/XCoLab

- microservices/clients/admin-client/src/main/java/org/xcolab/client/admin/attributes/configuration/ConfigurationAttributeKey.java
- microservices/services/admin-service/src/main/java/org/xcolab/service/admin/web/AdminController.java
- view/src/main/java/org/xcolab/view/pages/carouselwidget/CarouselController.java
- view/src/main/java/org/xcolab/view/pages/carouselwidget/CarouselPreferences.java
- view/src/main/java/org/xcolab/view/pages/carouselwidget/CarouselPreferencesController.java
- view/src/main/java/org/xcolab/view/pages/carouselwidget/LogoElement.java
- view/src/main/resources/static/sass/partials/_components.scss
- view/src/main/resources/static/sass/partials/components/_c-CarouselWrapper.scss
- view/src/main/webapp/WEB-INF/jsp/carouselwidget/editPreferences.jspx
- view/src/main/webapp/WEB-INF/jsp/carouselwidget/showCarousel.jspx
This PR implements the Logo Carousel Widget (COLAB-2013).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/18)
> [COLAB-2013] Logo Carousel Widget

- microservices/util/xcolab-utils/pom.xml
- microservices/util/xcolab-utils/src/main/java/org/xcolab/util/html/HtmlUtil.java
- microservices/util/xcolab-utils/src/test/java/org/xcolab/util/html/HtmlUtilTest.java
- pom.xml
- view/src/main/java/org/xcolab/view/pages/profile/view/UserProfileController.java
This PR implements the URL linkification on user bio submission.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/19)
> [COLAB-2088] Linkify URLs in User Bio

- view/src/main/java/org/xcolab/view/util/entity/ActivityUtil.java
- view/src/main/java/org/xcolab/view/util/entity/EntityGroupingUtil.java
This pull requests simplifies separate implementations to group entities into a map by using existing helper functions and removing redundant steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/42)
> [COLAB-2306] Simplify grouping functions

- view/src/main/java/org/xcolab/view/pages/proposals/requests/UpdateProposalDetailsBean.java
- view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails_edit.jspx
This PR increases the character limit for the team field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/61)
> [COLAB-2385] team name limit

- view/src/main/java/org/xcolab/view/pages/proposals/view/action/VoteOnProposalActionController.java
This PR fixes missing activity entries for voting activity by adding the respective calls in the controller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/64)
> [COLAB-2402] Voting activity not recorded

- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/service/proposal/ProposalVersionService.java
- view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/json/ProposalVersionsJsonController.java
- view/src/main/resources/static/js/proposals/historyWidget.js
This PR fixes the broken version pagination.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/66)
> [COLAB-2406] Bugfix: Version Pagination

- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/ProposalAttributeClient.java
- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/ProposalAttributeClientUtil.java
- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/ProposalClient.java
- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/AbstractProposal.java
- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/Proposal.java
- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/attributes/AbstractProposalAttribute.java
- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/attributes/ProposalAttribute.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/domain/proposal/ProposalDaoImpl.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/domain/proposalattribute/ProposalAttributeDaoImpl.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/domain/proposalversion/ProposalVersionDao.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/domain/proposalversion/ProposalVersionDaoImpl.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/helper/ProposalAttributeHelper.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/service/proposal/ProposalService.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/service/proposalattribute/ProposalAttributeService.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/web/ProposalsController.java
- sql/deployments/deployment-2017-10-26.sql
- sql/starter/xcolab-schema.sql
- view/src/main/java/org/xcolab/view/pages/proposals/impact/ProposalImpactSeries.java
- view/src/main/java/org/xcolab/view/pages/proposals/utils/edit/ProposalCreationUtil.java
- view/src/main/java/org/xcolab/view/pages/proposals/utils/edit/ProposalUpdateHelper.java
- view/src/main/java/org/xcolab/view/pages/proposals/view/action/ProposalRevertActionController.java
- view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/CreateProposalController.java
- view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/tabs/ProposalAdminTabController.java
This PR removes ProposalAttribute.versionWhenCreated and Proposal.currentVersion and changes the ProposalAttribute versioning system so that in each update, all updated attributes receive the same version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/62)
> [COLAB-2283] Proposal Versions Refactoring

- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/Proposal.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/domain/proposalversion/ProposalVersionDao.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/domain/proposalversion/ProposalVersionDaoImpl.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/service/proposalattribute/ProposalAttributeService.java
This PR fixes the bug where proposal updates were not working correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/67)
> Bugfix: [COLAB-2283] Update not working correctly

- view/src/main/resources/static/js/proposals/discussionComments.js
This PR fixes the broken comment editor when logged in as an admin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/81)
> [COLAB-2412] Fix comment editor

- view/src/main/resources/static/js/proposals/discussionComments.js
This PR fixes the comment countdown message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/83)
> [COLAB-2413] Fix comment countdown message

- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/pojo/Contest.java
- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/Proposal.java
- view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails.jspx
- view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails/header.jspx
- view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails_edit.jspx
This PR fixes the proposal logo URL generation (copying the method used for the contest logo). The proposal logo was still relative and Twitter requires absolute URLs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/88)
> [COLAB-2453] Fix twitter preview image

- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/pojo/templates/PlanSectionDefinition.java
This PR replaces some old, custom ID parsing code with our standardized method in the `IdListUtil`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/91)
> [COLAB-2461] Improve ID parsing in section definition

- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/pojo/evaluation/members/AbstractProposalVote.java
- microservices/clients/members-client/src/main/java/org/xcolab/client/members/pojo/Member.java
- microservices/services/contest-service/src/main/java/org/xcolab/service/proposal/domain/proposalvote/ProposalVoteDaoImpl.java
- microservices/util/entity-utils/src/main/java/org/xcolab/entity/utils/notifications/proposal/ProposalVoteValidityConfirmation.java
- sql/deployments/deployment-2017-12-13-COLAB-2493.sql
- sql/starter/xcolab-schema.sql
- view/src/main/java/org/xcolab/view/pages/proposals/utils/voting/VoteValidator.java
- view/src/main/java/org/xcolab/view/pages/proposals/view/action/VoteOnProposalActionController.java
This PR implements a few small changes to the vote validation system:
* it now stored the validation result (better to analysis)
* it now send confirmation emails to all previous voters as well
* it no longer invalidates similar names on shared IPs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/93)
> [COLAB-2493] vote validation

- view/gulpfile.js
- view/package.json
- view/pom.xml
- view/yarn.lock
This PR adds the ability to watch files with gulp using `gulp watch` and changes the default build to skips minification and adding prefixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/97)
> [COLAB-2523] Improve gulpfile

- view/src/main/java/org/xcolab/view/pages/contestmanagement/beans/ProposalReportBean.java
- view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/AdminTabController.java
- view/src/main/java/org/xcolab/view/pages/contestmanagement/utils/ContestCsvWriter.java
- view/src/main/java/org/xcolab/view/pages/contestmanagement/utils/ProposalCsvWriter.java
- view/src/main/java/org/xcolab/view/pages/contestmanagement/utils/VoteCsvWriter.java
- view/src/main/java/org/xcolab/view/pages/proposals/view/proposal/tabs/ProposalAdminTabController.java
- view/src/main/webapp/WEB-INF/jsp/contestmanagement/manager/adminTab.jspx
This PR adds two new CSV exports to download basic info from the platform. They work similarly to the existing voting report function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/106)
> [COLAB-2534] Proposal contest export

- microservices/clients/members-client/src/main/java/org/xcolab/client/members/MembersClient.java
- view/src/main/java/org/xcolab/view/pages/profile/view/UserProfileController.java
This PR fixes the user deletion feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/104)
> [COLAB-2507] Bugfix: Delete Member

- view/src/main/webapp/WEB-INF/jsp/profile/editUserProfile.jspx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/117)
> [COLAB-2391] Hide SSO buttons on profile edit page

- view/src/main/resources/i18n/colab_es.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/144)
> Spelling changes

- view/src/main/resources/i18n/homepage_es.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/146)
> Change Spanish About translation

- view/src/main/resources/i18n/community_es.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/147)
> Translate members download to Spanish

- view/src/main/java/org/xcolab/view/pages/profile/beans/MessageBean.java
- view/src/main/webapp/WEB-INF/jsp/profile/showUserProfile.jspx
I found this bug (see Jira issue) and developed a solution for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/149)
> [COLAB-2882] Correct message links - user profile inbox

- microservices/services/members-service/src/main/resources/db/migration/V4__COLAB-2895-update-staff.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/155)
> [COLAB-2895]: update staff members

- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/MembershipClient.java
- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/proposals/MembershipClientUtil.java
- microservices/services/contest-service/src/main/resources/db/migration/V8__COLAB-2899-remove-groupId.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/156)
> [COLAB-2899]: groupId <-> proposalId mixup

- microservices/clients/contents-client/src/main/java/org/xcolab/client/contents/ContentsClient.java
- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/ContestClient.java
- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/pojo/Contest.java
- view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/details/AbstractTabController.java
- view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/details/ResourcesTabController.java
- view/src/main/java/org/xcolab/view/pages/contestmanagement/wrappers/WikiPageWrapper.java
- view/src/main/webapp/WEB-INF/jsp/contestmanagement/details/action.jspx
- view/src/main/webapp/WEB-INF/jsp/contestmanagement/details/resourcesTab.jspx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/158)
> [COLAB-2430]: disable resource tab

- view/src/main/webapp/WEB-INF/jsp/proposals/proposalDetails/proposalJudging.jspx
Wasn't able to test it, because no contest is in judging phase
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/163)
> [COLAB-2783]: update language

- view/src/main/java/org/xcolab/view/pages/discussion/discussions/views/CategoryController.java
- view/src/main/webapp/WEB-INF/jsp/discussion/category.jspx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/164)
> [COLAB-2915]: change default to descending for the category page

- view/src/main/java/org/xcolab/view/activityentry/contest/ContestBaseActivityEntry.java
- view/src/main/java/org/xcolab/view/activityentry/discussion/DiscussionAddedActivityEntry.java
- view/src/main/java/org/xcolab/view/activityentry/discussion/DiscussionBaseActivityEntry.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/166)
> [COLAB-2729]: remove variable which is never set but accessed at sometime

- microservices/clients/contestproposal-client/src/main/java/org/xcolab/client/contest/ContestClient.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/168)
> [COLAB-2924]: sql cannot be null exception

- view/src/main/java/org/xcolab/view/pages/proposals/discussion/ProposalDiscussionPermissions.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/170)
> [COLAB-2856]: fix bug: admins weren't allowed to add comments

- view/src/main/java/org/xcolab/view/pages/messaging/beans/SendMessageBean.java
- view/src/main/java/org/xcolab/view/pages/profile/beans/MessageBean.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/177)
> remove honeypot references

- view/src/main/java/org/xcolab/view/pages/profile/view/UserProfileController.java
- view/src/main/webapp/WEB-INF/jsp/profile/showUserProfile.jspx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/178)
> [COLAB-2932]: create UserProfileBean only when the profile is active

- view/src/main/java/org/xcolab/view/pages/discussion/discussions/views/CategoryController.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/200)
> [COLAB-2963] add default sort value to discussion thread

- view/src/main/java/org/xcolab/view/pages/contestmanagement/controller/manager/FlaggingTabController.java
- view/src/main/webapp/WEB-INF/jsp/members/users.jspx
Small fixes in FlagginTabController and users.jspx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cci-mit/xcolab/204)
> Colab 2977 bug fix
